{"name": "test_inc", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 4\n +  where 3 = inc(1)", "trace": "def test_inc():\n>       assert inc(1)   == 4\nE       assert 3 == 4\nE        +  where 3 = inc(1)\n\ntest_pytest.py:7: AssertionError"}, "start": 1617092430771, "stop": 1617092430773, "uuid": "5cb45ada-1b8b-4113-be98-34ff1d3e1338", "historyId": "d6cbe0167730598efb5d701b5f5205b3", "testCaseId": "dad539c665de1b4e7ac0ddc758571dcd", "fullName": "test_pytest#test_inc", "labels": [{"name": "suite", "value": "test_pytest"}, {"name": "host", "value": "tedu"}, {"name": "thread", "value": "35766-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest"}]}