{"name": "test_inc", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 4\n +  where 3 = inc(1)", "trace": "def test_inc():\n>       assert inc(1)   == 4\nE       assert 3 == 4\nE        +  where 3 = inc(1)\n\ntest_pytest.py:7: AssertionError"}, "start": 1617091521969, "stop": 1617091521970, "uuid": "cc834eff-0796-4731-9e33-dcdbb16d53f9", "historyId": "d6cbe0167730598efb5d701b5f5205b3", "testCaseId": "dad539c665de1b4e7ac0ddc758571dcd", "fullName": "test_pytest#test_inc", "labels": [{"name": "suite", "value": "test_pytest"}, {"name": "host", "value": "tedu"}, {"name": "thread", "value": "35302-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest"}]}